### ISSUE TITLE
ARP Sniffing doesnt work for me

### ISSUE THREAD

**Issue by CookieCash** [pinae/dashbutton#2]
I get the following Error after starting the script the first time:
`pi@raspberrypi:~ $ sudo python2 listen.py
WARNING: No route found for IPv6 destination :: (no default route?)
Listening for ARP packets...
Traceback (most recent call last):
  File "listen.py", line 26, in <module>
    sniff(prn=arp_received, iface="wlan0", filter="arp", store=0, count=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "listen.py", line 10, in arp_received
    if packet[ARP].op == 1 and packet[ARP].hwdst == '00:00:00:00:00:00':
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 770, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [ARP] not found
`

**Comment by dl8bb** [comment]
Saw this from time to time too. Start the listen.py again. For me it was fixed after the 3rd try ;-)

**Comment by CookieCash** [comment]
Now it works, thanks.
Can you explain how to setup the script to work with IFTTT? I got the MAC
adress and my maker key.
Thanks

Am 07.11.2016 1:21 PM schrieb "dl8bb" notifications@github.com:

**Comment by dl8bb** [comment]
Hmmm... go back to ifttt and create a event. Finish your receipt or now called Applet. You'll get a URL like this:

`https://maker.ifttt.com/trigger/<_YOUR_EVENT_>/with/key/<_YOUR_KEY_>
`

Open listen.py and insert your url into the call of the requests.get()-method

`requests.get("https://maker.ifttt.com/trigger/<_YOUR_EVENT_>/with/key/<_YOUR_KEY_>")
`

Replace **<_YOUR_KEY_>** and **<_YOUR_EVENT_>** with the values you got from ifttt.

Remove the comment hash # in front of the **requests.get()**

**Comment by CookieCash** [comment]
I inserted the Maker key and MAC adress,
I removed `from send_mail import send_mail  # This function sends mails directly` and the Hash in front of request.get and import requests 
Now i get this error:
`pi@raspberrypi:~ $ sudo python2 listen.py
WARNING: No route found for IPv6 destination :: (no default route?)
Listening for ARP packets...
Traceback (most recent call last):
  File "listen.py", line 26, in <module>
    sniff(prn=arp_received, iface="wlan0", filter="arp", store=0, count=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "listen.py", line 10, in arp_received
    if packet[ARP].op == 1 and packet[ARP].hwdst == '00:00:00:00:00:00':
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 770, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [ARP] not found
`

**Comment by dl8bb** [comment]
Try again! You may deactivate ipv6 but not sure if if will help.
